// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Crosstyan",
            "url": "github.com/crosstyan/mqtt-to-ws/",
            "email": "crosstyan@outlook.com"
        },
        "license": {
            "name": "WTFPL",
            "url": "http://www.wtfpl.net/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/humidity": {
            "get": {
                "description": "get Temperature/Humidity by page",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MQTTRecords"
                ],
                "summary": "Get Temperature/Humidity Records by Page",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "From 1 to infinity",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "get Temperature/Humidity by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MQTTRecords"
                ],
                "summary": "Get Temperature/Humidity Records by Date",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DateRangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        },
        "/temperature": {
            "get": {
                "description": "get Temperature/Humidity by page",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MQTTRecords"
                ],
                "summary": "Get Temperature/Humidity Records by Page",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "From 1 to infinity",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "get Temperature/Humidity by date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MQTTRecords"
                ],
                "summary": "Get Temperature/Humidity Records by Date",
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DateRangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseMsg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.DateRangeRequest": {
            "type": "object",
            "required": [
                "start"
            ],
            "properties": {
                "end": {
                    "description": "Time RFC3339",
                    "type": "string",
                    "example": "2022-01-01T00:00:00Z"
                },
                "page": {
                    "description": "Page is from 1 to infinity",
                    "type": "integer",
                    "example": 1
                },
                "start": {
                    "description": "Time RFC3339",
                    "type": "string",
                    "example": "2020-01-01T00:00:00Z"
                }
            }
        },
        "controller.ErrorMsg": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message",
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "controller.ResponseMsg": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MQTTRecord"
                    }
                }
            }
        },
        "model.MQTTRecord": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "number",
                    "example": 24.23
                },
                "timestamp": {
                    "description": "Time RFC3339",
                    "type": "string",
                    "example": "2020-01-01T00:00:00Z"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server celler server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
